# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: tecwindow.Albayan
PackageVersion: 1.2.1
PackageLocale: ar-SA
Publisher: tecwindow
PublisherUrl: https://tecwindow.net/
PublisherSupportUrl: https://tecwindow.net/en/contact
Author: tecwindow
PackageName: Albayan
PackageUrl: https://github.com/tecwindow/albayan
License: GNU General Public License
Copyright: copyright, ©2023; tecwindow
ShortDescription: Albayan كل ما يخص الإسلام.
Tags:
- islamic
- islam
- quran
- desktop
- alquran
InstallationNotes: Thank you for using Albayan. If you need support at any time, you can contact us via the help menu within the program.
ManifestType: defaultLocale
ManifestVersion: 1.6.0
